"""create userauth table

Revision ID: 7592c7224614
Revises: 3dae67951e5c
Create Date: 2022-12-15 10:37:14.469500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7592c7224614"
down_revision = "3dae67951e5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userauth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userauth_id"), "userauth", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userauth_id"), table_name="userauth")
    op.drop_table("userauth")
    # ### end Alembic commands ###
